config/routes.rb
Rails.application.routes.draw do
  resources :phrases do
    collection do
      get 'search'
      get 'home' => 'home#index'
    end
    member do
      get 'history'
    end
    get :autocomplete_phrase_expression, :on => :collection
  end
  resources :tests do
    collection do
      get 'tests' => 'tests#index'
      get 'edit' => 'tests#edit'
    end
  end
  devise_for :users
   root 'home#index'
end

app/models/phrase.rb
# == Schema Information
#
# Table name: phrases
#
#  id         :integer          not null, primary key
#  expression :string
#  meaning    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Phrase < ActiveRecord::Base
  include PgSearch
  PgSearch.multisearch_options = { :using => { :tsearch => {:prefix => true} } }
  multisearchable :against => [:expression, :meaning]
  has_paper_trail :on => [:update]
  belongs_to :user
  validates :expression, :meaning, presence: true
end

app/models/test.rb
# == Schema Information
#
# Table name: tests
#
#  id         :integer          not null, primary key
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Test < ActiveRecord::Base
  validates :content, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  admin                  :boolean          default(FALSE)
#  first_name             :string
#  last_name              :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :phrases, dependent: :destroy

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        << :first_name
    devise_parameter_sanitizer.for(:sign_up)        << :last_name
    devise_parameter_sanitizer.for(:account_update) << :first_name
    devise_parameter_sanitizer.for(:account_update) << :last_name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/phrases_controller.rb
# == Schema Information
#
# Table name: phrases
#
#  id         :integer          not null, primary key
#  expression :string
#  meaning    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PhrasesController < ApplicationController
  before_action :set_phrase, only: [:show, :edit, :update, :destroy, :history]
  before_action :check_user, only: [:edit, :update, :destroy]
  autocomplete :phrase, :expression

  def search
    if params[:search].present?
      @phrases = PgSearch.multisearch(params[:search]).paginate(:page => params[:page], :per_page => 4)
    end
  end
  # GET /phrases
  # GET /phrases.json
  def index
    respond_to do |format|
      format.html { @phrases = Phrase.paginate(page: params[:page], per_page: 4) }
      format.json { @phrases = Phrase.all }
    end
  end

  # GET /phrases/new
  def new
    @phrase = Phrase.new
  end

  # POST /phrases
  # POST /phrases.json
  def create
    @phrase = Phrase.new(phrase_params)

    respond_to do |format|
      if @phrase.save
        format.html { redirect_to @phrase, notice: 'Pomyślnie dodano.' }
        format.json { render :show, status: :created, location: @phrase }
      else
        format.html { render :new }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phrases/1
  # PATCH/PUT /phrases/1.json
  def update
    respond_to do |format|
      if @phrase.update(phrase_params)
        format.html { redirect_to @phrase, notice: 'Pomyślnie zaktualizowano.' }
        format.json { render :show, status: :ok, location: @phrase }
      else
        format.html { render :edit }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phrases/1
  # DELETE /phrases/1.json
  def destroy
    @phrase.destroy
    respond_to do |format|
      format.html { redirect_to phrases_url, notice: 'Pomyślnie usunięto.' }
      format.json { head :no_content }
    end
  end

  def history
    #unscoped - returns a scope for the model without the previously set scopes
    @versions = @phrase.versions.merge(PaperTrail::Version.unscope(:order)).order('created_at DESC').paginate(:page => params[:page], :per_page => 5)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phrase
      @phrase = Phrase.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def phrase_params
      params.require(:phrase).permit(:expression, :meaning)
    end

    def check_user
      unless (current_user && current_user.admin?)
        redirect_to phrases_path, alert: "Nie masz uprawnień admina!"
    end
end
end

app/controllers/tests_controller.rb
# == Schema Information
#
# Table name: tests
#
#  id         :integer          not null, primary key
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class TestsController < ApplicationController
  before_action :set_test, only: [:edit,:update]
  before_action :check_user, only: [:update]

  def index
    @tests = Test.all
  end

  def update
      if @test.update(test_params)
        redirect_to tests_path, notice: 'Pomyślnie zaktualizowano.'
      end
  end

  # def show
  #   @test = Test.find(params[:id])
  # end
  private
    def set_test
      @test = Test.find(params[:id])
    end

    def test_params
      params.require(:test).permit(:content)
    end

    def check_user
      unless (current_user && current_user.admin?)
        redirect_to phrases_path, alert: "Nie masz uprawnień admina!"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/phrases_helper.rb
# == Schema Information
#
# Table name: phrases
#
#  id         :integer          not null, primary key
#  expression :string
#  meaning    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module PhrasesHelper
require "html_truncator"
end

app/helpers/tests_helper.rb
# == Schema Information
#
# Table name: tests
#
#  id         :integer          not null, primary key
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module TestsHelper
end

app/views/home/index.html.haml
#searchbar.row.col-md-12.center-block
  - if user_signed_in?
    %h2.text-center
      Cześć
      =current_user.first_name
    %h5.text-center Co dziś potrzebujesz znaleźć?
  - else
    %h2.text-center Dictionary
    %h5.text-center United Ideas
  = render "layouts/searchbar"

app/views/layouts/_bootstrap.html.haml
/ Latest compiled and minified CSS
%link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css", :integrity => "sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7", :rel => "stylesheet"}
/ Optional theme
%link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css", :integrity => "sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r", :rel => "stylesheet"}
/ Latest compiled and minified jQuery
%script{:src => "//code.jquery.com/jquery-2.2.0.min.js"}
/ Latest compiled and minified JavaScript
%script{:crossorigin => "anonymous", :integrity => "sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS", :src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"}

app/views/layouts/_footer.html.haml
%footer.footer.text-center
  %p &copy; UnitedIdeas #{Date.today.year}

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-custom
  .container-fluid
    .navbar-header
      = link_to "Dictionary", root_path, :class => "navbar-brand"
    %ul.nav.navbar-nav.navbar-right
      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          %span.glyphicon.glyphicon-align-justify
          %span.caret
        %ul.dropdown-menu
          %li
            = link_to "Słownik", phrases_path
          -if user_signed_in?
            %li
              = link_to 'Testy aplikacji', tests_path
            %li
              = link_to "Edytuj Profil", edit_user_registration_path
            %li
              = link_to "Wyloguj", destroy_user_session_path, method: :delete
          -else
            %li
              = link_to "Zaloguj się", new_user_session_path

app/views/layouts/_searchbar.html.haml
= form_tag search_phrases_path, method: :get do
  #custom-search-input
    .input-group.col-md-12
      = text_field_tag :search, params[:search], class: "search-query form-control", :placeholder => "Szukaj...", "data-autocomplete" => autocomplete_phrase_expression_phrases_path, 'data-auto-focus' => true
      %span.input-group-btn
        %button.btn.btn-danger{:type => "submit"}
          %i.glyphicon.glyphicon-search

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Dictionary
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "//fonts.googleapis.com/css?family=Montserrat:400,700", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "//fonts.googleapis.com/css?family=Bree+Serif&subset=latin,latin-ext", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "http://netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.css", :rel => "stylesheet"}
    = render "layouts/bootstrap"
  %body
    = render "layouts/navbar"
    .container
      - flash.each do |name, msg|
        - if msg.is_a?(String)
          %div{:class => "alert alert-#{name == "notice" ? "success" : "danger"} alert-dismissable"}
            %button.close{"data-dismiss" => "alert", :type => "button"}
              %span{"aria-hidden" => "true"} &times;
              %span.sr-only Close
            = content_tag :div, msg, :id => "flash_#{name}"
      = yield
    = render "layouts/footer"

app/views/phrases/_form.html.haml
= tinymce
= simple_form_for @phrase do |f|
  - if @phrase.errors.any?
    #error_explanation.alert.alert-danger.alert-dismissable
      %button.close{"data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} &times;
        %span.sr-only Close

      %h4= "#{@phrase.errors.count} błędy:"
      %ul
        - @phrase.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :expression, placeholder: "Wpisz nazwę...", class: "form-control"

  .form-group
    = f.text_area :meaning, class: 'form-control tinymce', rows: 10, placeholder: "Wpisz treść..."
  .form-group.text-right
    = link_to :back, class: "btn btn-primary" do
      %i.glyphicon.glyphicon-chevron-left

    = f.button :submit, class: "btn btn-success"
:javascript
  tinyMCE.init({
    selector: 'textarea'
    language: 'pl'
  });

app/views/phrases/edit.html.haml
%h1 Edycja hasła
= tinymce_assets
= render 'form'

app/views/phrases/history.html.haml
-if @versions.blank?
  .alert.alert-info
    %a.close{"aria-label" => "close", "data-dismiss" => "alert", :href => "#"} &times;
    Brak historii haseł.
-else
  %h1
    Historia hasła
  %h3
    Wyrażenie:
    = @phrase.expression
  %h5
    Edytowano
    = @phrase.versions.count
    razy.
  %table.table
    %thead
      %tr
        %th
          Data
        %th
          Zmiany
    %tbody
      - @versions.each do |version|
        %tr
          %td
            = l(version.created_at, format: "%-d.%m.%Y")
          %td
            = HTML_Truncator.truncate(version.reify.meaning, 40).html_safe
  = will_paginate @versions

app/views/phrases/index.html.haml
.searchbar_min
  = render "layouts/searchbar"
= will_paginate
.panel.panel-primary.filterable
  .panel-heading
    %h3.panel-title Słownik
    .pull-right
      %button.btn.btn-default.btn-xs.btn-filter
        %span.glyphicon.glyphicon-filter
        Filtr
  %table.table
    %thead
      %tr.filters
        %th
          %input.form-control{:disabled => "", :placeholder => "Wyrażenie", :type => "text"}
        %th
          %input.form-control{:disabled => "", :placeholder => "Znaczenie", :type => "text"}
        %th

    %tbody
      - @phrases.each do |phrase|
        %tr
          %td= phrase.expression
          %td= HTML_Truncator.truncate(phrase.meaning, 40).html_safe
          %td
            = link_to phrase, class: "btn btn-link" do
              %i.glyphicon.glyphicon-eye-open
              Pokaż
          -if current_user && current_user.admin?
            %td
              = link_to edit_phrase_path(phrase), class: "btn btn-link" do
                %i.glyphicon.glyphicon-edit
                Edytuj
            %td
              = link_to phrase, :method => :delete, :data => { :confirm => 'Jesteś pewny/a?' }, class: "btn btn-link" do
                %i.glyphicon.glyphicon-trash
                Usuń
%br
  = will_paginate
= link_to new_phrase_path, class: "btn btn-success" do
  %i.glyphicon.glyphicon-plus
  Dodaj hasło

app/views/phrases/new.html.haml
%h1 Dodawanie hasła

= render 'form'

app/views/phrases/search.html.haml
.searchbar_min
  = render 'layouts/searchbar'
-if @phrases.blank?
  .alert.alert-info
    %a.close{"aria-label" => "close", "data-dismiss" => "alert", :href => "#"} &times;
    Brak rezultatów.
-else
  %table.table.table-striped
    %thead
      %tr
        %th Wyrażenie
        %th Znaczenie

    %tbody
      = will_paginate @phrases
      - @phrases.each do |phrase|
        %tr
          %td= phrase.searchable.expression
          %td= HTML_Truncator.truncate(phrase.searchable.meaning, 40).html_safe
          %td
            = link_to phrase_path(phrase), class: "btn btn-link" do
              %i.glyphicon.glyphicon-eye-open
              Pokaż
          -if current_user && current_user.admin?
            %td
              = link_to edit_phrase_path(phrase), class: "btn btn-link" do
                %i.glyphicon.glyphicon-edit
                Edytuj
            %td
              = link_to phrase_path(phrase), :method => :delete, :data => { :confirm => 'Jesteś pewny/a?' }, class: "btn btn-link" do
                %i.glyphicon.glyphicon-trash
                Usuń
  %br
    = will_paginate @phrases

app/views/phrases/show.html.haml
.searchbar_min
  = render 'layouts/searchbar'
= link_to :back, class: "btn btn-primary" do
  %i.glyphicon.glyphicon-chevron-left
  Wróć
%p
  %h2
    = @phrase.expression
%p
  = @phrase.meaning.html_safe

-if current_user && current_user.admin?
  = link_to phrase_path(@phrase), :method => :delete, :data => { :confirm => 'Jesteś pewny/a?' }, class: "btn btn-danger" do
    %i.glyphicon.glyphicon-trash
    Usuń
  = link_to edit_phrase_path(@phrase), class: "btn btn-primary" do
    %i.glyphicon.glyphicon-pencil
    Edytuj
-unless @phrase.versions.blank?
  = link_to history_phrase_path(@phrase), class: "btn btn-primary" do
    %i.glyphicon.glyphicon-list-alt
    Historia